### ISSUE TITLE
Convey friendship and community aspect of DxE Philly

### ISSUE THREAD

**Issue by alexgleason** [directactioneverywhere/dxephilly.org#5]
One concern I have is that people may look at this site and not realize how chill we are outside of protesting. It might entice people to join more if they know they can also make friends with us. It may help to show some pics of us just goofing around and/or eating food too so newcomers know they can make friends in addition to protesting.

**Comment by keiradevine4** [comment]
I like this a lot. One of the main aspects of DxE is meetups, friendship and community. We do have a album on the FB page titled 'Meetups'.

**Comment by alexgleason** [comment]
Cool, I see the [meetups album](https://www.facebook.com/media/set/?set=a.869150983184142.1073741834.728622937236948&type=3). Leaving it here for future reference.

Wondering the best way to display this. It could be:

1. A separate section with images and a description
2. Just incorporate some of these pictures into the top banner

**Comment by alexgleason** [comment]
I feel like we've done this with the new slideshow.
